Initial commit of azure supplemental values file
ni/install-systemlink-enterprise pull request #218
Opened 2024-08-28 17:47 UTC by ts-reed-ni

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/install-systemlink-enterprise/blob/master/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/install-systemlink-enterprise/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This PR add the supplemental values file for azure app gateway ingress and service health paths

### Why should this Pull Request be merged?

Provide customers with the ingress and health check annotations template to speed up deployment of environments in Azure.

### What testing has been done?

Deployed an Azure environment manually using this supplemental values file and verified that the services start correctly with successful health checks.

2024-08-28 17:50 UTC, JD-Robertson approved these changes

2024-08-28 17:51 UTC, BKnight760 requested changes

2024-08-28 17:51 UTC, BKnight760 commented on getting-started/templates/Azure/azure_supplemental_values
> +        #appgw.ingress.kubernetes.io/appgw-ssl-profile: "stratus-dev",
Consider systemlink-ssl-profile instead

2024-08-28 17:51 UTC, BKnight760 commented on getting-started/templates/Azure/azure_supplemental_values
> +        appgw.ingress.kubernetes.io/appgw-ssl-certificate: "stratus-dev-cert"
Consider systemlink-ssl-cert instead.

2024-08-28 17:51 UTC, BKnight760 commented on getting-started/templates/Azure/azure_supplemental_values
> +        #appgw.ingress.kubernetes.io/appgw-ssl-profile: "stratus-dev",
same name as above.

2024-08-28 17:51 UTC, BKnight760 commented on getting-started/templates/Azure/azure_supplemental_values
> +        appgw.ingress.kubernetes.io/appgw-ssl-certificate: "stratus-dev-cert"
Same name as above.

2024-08-28 17:51 UTC, BKnight760 commented on getting-started/templates/Azure/azure_supplemental_values
> +global:
Add a comment block to the top that describes what this file is and how it should be used.

2024-08-29 16:07 UTC, BKnight760 approved these changes

2024-08-29 16:07 UTC, merged